repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: pretty-format-json
      args: [ --autofix, --no-sort-keys ]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format